### ISSUE TITLE
cue_binary feels off

### ISSUE THREAD

**Issue by steeve** [tnarg/rules_cue#2]
I feel `cue_export` would be closer to what, as a user, I had expected.

**Comment by tnarg** [comment]
I debated this. As a cue user I would expect it to be called cue_export. As a bazel user, you have examples of `sass_binary` and `postcss_binary` producing .css files from official rules_* repositories. I just did a broader survey and found rules_jsonnet has jsonnet_to_json, so maybe cue_export is a good choice.

**Comment by steeve** [comment]
That's a very good point, and I must say I'm slightly confused as a result. On the other hand, I'd stick as close to cue as possible, coming in as a regular user (and having written some early cue rules myself).

All in all, thank you for this!
